const main = () => {
    try {
        codigo     
    } catch (error) {
        console.log(`Deu erro no código, e o erro é esse ${error}`)
    } finally {
        console.info("Esse código sempre será mostrado")
    }
    
}

main()